### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by packituz-gttz** [Antonio-Diaz/fastapi-nosql-scraper#1]
Scrapping:

1.  Agregar los siguientes argumentos [aqui](https://github.com/Antonio-Diaz/fastapi-nosql-scraper/blob/e76b18276b486a4de51c182acdb31526290f2465/app/scraper.py#L20) para evitar la deteccion como scraper:
```
        self.options.add_argument('--disable-blink-features=AutomationControlled')
        self.options.add_experimental_option("excludeSwitches", ["enable-automation"])
        self.options.add_experimental_option('useAutomationExtension', False)
        self.options.add_argument('--window-size=1920,1080')
        self.options.add_argument("--start-maximized")
```
2. Encapsular Selenium con alguna librería como [selenium-stealth](https://github.com/diprajpatra/selenium-stealth) o [undetectabe-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) puedes validar si tu navegador es detectado como bot [aqui](https://intoli.com/blog/making-chrome-headless-undetectable/chrome-headless-test.html), entre mas campos en verde se vean mejor.
3. Sugiero usar pre-commit para solucionar problemas de código de manera automatica, yo uso esta configuracion:
```
default_stages: [ commit ]
fail_fast: false

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln
        args: [ --all ]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8-naming
        additional_dependencies:
          - flake8-variables-names
          - flake8-use-fstring
          - flake8-bugbear
          - flake8-simplify
          - flake8-comprehensions
          - pep8-naming

```

4. Agregar bandera --max-tasks-per-child=n en [celery](https://github.com/Antonio-Diaz/fastapi-nosql-scraper/blob/e76b18276b486a4de51c182acdb31526290f2465/app/worker.py#L52) para que cada n ejecuciones se genere un nuevo worker y asi evitar problemas de memoria.
